export const userBioData = [
  {
    id: "first_name",
    name: "first_name",
    placeholder: "Enter First Name",
    type: "text",
    label: "First Name",
  },
  {
    id: "last_name",
    name: "last_name",
    placeholder: "Enter Last Name",
    type: "text",
    label: "Last Name",
  },
  {
    id: "email",
    name: "email",
    placeholder: "Enter Email",
    type: "email",
    label: "Email",
  },
  {
    id: "company_name",
    name: "company_name",
    placeholder: "Enter Company's Name",
    type: "text",
    label: "Company's Name",
  },
  {
    id: "company_location",
    name: "company_location",
    placeholder: "Enter Company's Location",
    type: "text",
    label: "Company's Location",
  },
  {
    id: "company_role",
    name: "company_role",
    placeholder: "Enter Company's Role",
    type: "text",
    label: "Company's Role",
  },
  {
    id: "address",
    name: "address",
    placeholder: "Enter Address",
    type: "text",
    label: "Address",
  },
  {
    id: "phone",
    name: "phone",
    placeholder: "Enter Phone",
    type: "text",
    label: "Phone",
  },
];
