"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Provider } from "react-redux";
import store from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <Provider store={store}>
            <ToastContainer
              position="top-center"
              pauseOnHover={false}
              closeOnClick
              closeButton={true}
            />
            <div>
              <div>{children}</div>
            </div>
        </Provider>
      </body>
    </html>
  );
}
